version: '3.1'
services:
  online-code-editor-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: online-code-editor-frontend
    ports:
      - "8082:80"