version: '3.1'
services:
  online-code-editor-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: online-code-editor-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
networks:
  default:
    external:
      name: nginx-proxy